Views project
dev89s/blog-app pull request #6
Opened 2023-07-19 19:59 UTC by dev89s

Added 4 views for 4 routes:
1. users#index
2. users#show
3. posts#index
4. posts#show

Followed the wireframe's design

Tested with data and assured that it works properly.

2023-07-19 22:01 UTC, addod19 requested changes
### Hi @dev89s, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Correct Git-flow followed :100: 
- [ ] README file is professional :1st_place_medal: 
- [ ] Nice use of partials :rocket: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 22:01 UTC, addod19 commented on app/views/users/index.html.erb
> +  <div class='user-list'>
- [x] It would be better if we can click any of the users to be redirected to the users show page as seen in the [wireframe](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/blog-app/images/blog_user_page.png?token=GHSAT0AAAAAACBSEKEGCKCLHVQJUSAWBNDGZFYNCKQ). Currently, we are unable to click on any user to get that functionality.

2023-07-19 22:01 UTC, addod19 commented on app/views/users/show.html.erb
>  <br>
- [x] It would be better if there is a `See all posts` link that when clicked redirects us to the Post index page as seen in the [wireframe](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/blog-app/images/blog_user_all_posts.png?token=GHSAT0AAAAAACBSEKEGOZ5ENE5Y3XEKJYUSZFYNEKQ)

2023-07-19 22:01 UTC, addod19 commented on app/views/posts/index.html.erb
> +  </section>
- [x] It would be better if we implement `post.recent_comments` method to render 5 most recent comments in the post index view as seen in the wireframe

2023-07-19 22:01 UTC, addod19 commented on app/views/posts/show.html.erb
> +  </div>
- [ ] Post show page should display post with all comments listed as shown on the [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_single_post.png)Post show page displays post with all comments listed as shown on the [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_single_post.png). Currently, I'm not able to test it in the views of the app

2023-07-20 11:52 UTC, franclobo requested changes
Hi @dev89s, 

# Required Changes ♻️

![istockphoto-1079018918-612x612](https://github.com/dev89s/blog-app/assets/58642949/c89396af-50d7-4191-8074-5f402fb49087)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Git flow ✔️
- Good UI ✔️  


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 11:52 UTC, franclobo commented on app/views/posts/index.html.erb
> +  </section>
As requested by the previous CR in the post index page, it should show the last 5 comments as shown in the wireframe, Currently, it is showing all the comments although it doesn't are from the current post.

| Wireframe | Your design |
|---|---|
|![image](https://github.com/dev89s/blog-app/assets/58642949/387c6818-1d71-4f0b-bc2c-e1be99544741) | ![image](https://github.com/dev89s/blog-app/assets/58642949/1dd90c5f-9527-48fc-b646-a8e23623e651) |

2023-07-20 11:52 UTC, franclobo commented on app/views/posts/show.html.erb
> +  </div>
- [ ] As requested by the previous CR the post-show page should show all the comments on the post, currently, I can see 5 of them.

| Wureframe | Your design |
|---|---|
| ![image](https://github.com/dev89s/blog-app/assets/58642949/19be83f4-75cf-4011-a326-814d1e9691ab) | ![image](https://github.com/dev89s/blog-app/assets/58642949/04de387e-a5cf-4d51-8fc3-af79dc6ef216) |

2023-07-20 15:09 UTC, VICTOR-CHUKWU approved these changes
Hi @dev89s , 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] All linters passed
- [ ] view works correctly

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 15:09 UTC, merged